//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGC.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NGC.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        internal static string ConnectWithMicrosoft {
            get {
                return ResourceManager.GetString("ConnectWithMicrosoft", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        internal static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        internal static string Opportunities {
            get {
                return ResourceManager.GetString("Opportunities", resourceCulture);
            }
        }
        
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string ProspectMap {
            get {
                return ResourceManager.GetString("ProspectMap", resourceCulture);
            }
        }
        
        internal static string ConsultContact {
            get {
                return ResourceManager.GetString("ConsultContact", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string Qualifications {
            get {
                return ResourceManager.GetString("Qualifications", resourceCulture);
            }
        }
        
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        internal static string SourceCollection {
            get {
                return ResourceManager.GetString("SourceCollection", resourceCulture);
            }
        }
        
        internal static string EnableCheckIn {
            get {
                return ResourceManager.GetString("EnableCheckIn", resourceCulture);
            }
        }
        
        internal static string NewNote {
            get {
                return ResourceManager.GetString("NewNote", resourceCulture);
            }
        }
        
        internal static string NoteRequired {
            get {
                return ResourceManager.GetString("NoteRequired", resourceCulture);
            }
        }
        
        internal static string DateReminder {
            get {
                return ResourceManager.GetString("DateReminder", resourceCulture);
            }
        }
        
        internal static string ContainsPersonalData {
            get {
                return ResourceManager.GetString("ContainsPersonalData", resourceCulture);
            }
        }
        
        internal static string NewOpportunity {
            get {
                return ResourceManager.GetString("NewOpportunity", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string Opportunity {
            get {
                return ResourceManager.GetString("Opportunity", resourceCulture);
            }
        }
        
        internal static string NoOpportunity {
            get {
                return ResourceManager.GetString("NoOpportunity", resourceCulture);
            }
        }
        
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string CGU {
            get {
                return ResourceManager.GetString("CGU", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string LoginCredentialsEmpty {
            get {
                return ResourceManager.GetString("LoginCredentialsEmpty", resourceCulture);
            }
        }
        
        internal static string PasswordSent {
            get {
                return ResourceManager.GetString("PasswordSent", resourceCulture);
            }
        }
        
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string Siret {
            get {
                return ResourceManager.GetString("Siret", resourceCulture);
            }
        }
        
        internal static string StatutJuridique {
            get {
                return ResourceManager.GetString("StatutJuridique", resourceCulture);
            }
        }
        
        internal static string APE {
            get {
                return ResourceManager.GetString("APE", resourceCulture);
            }
        }
        
        internal static string APELabel {
            get {
                return ResourceManager.GetString("APELabel", resourceCulture);
            }
        }
        
        internal static string APEClass {
            get {
                return ResourceManager.GetString("APEClass", resourceCulture);
            }
        }
        
        internal static string Effectifs {
            get {
                return ResourceManager.GetString("Effectifs", resourceCulture);
            }
        }
        
        internal static string LocationNotFound {
            get {
                return ResourceManager.GetString("LocationNotFound", resourceCulture);
            }
        }
        
        internal static string SearchCompany {
            get {
                return ResourceManager.GetString("SearchCompany", resourceCulture);
            }
        }
        
        internal static string ResultsOpenData {
            get {
                return ResourceManager.GetString("ResultsOpenData", resourceCulture);
            }
        }
        
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
    }
}
